version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: service-users-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/users-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - mongo-network

volumes:
  mongo-data:

networks:
  mongo-network:
    driver: bridge